server:
  port: 8080

spring:
  application:
    name: finalProjectSpringBoot

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/third_db?userSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password: 

  jpa:
    database:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
      format_sql: true

  sql:
    init:
      mode: always

# 필요 시 업로드 file 경로
#file.upload-dir= /~